///////////////////////////////////////////////////////////
//  Roue.cs
//  Implementation of the Class Roue
//  Generated by Enterprise Architect
//  Created on:      14-juin-2021 16:28:19
//  Original author: sophi
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;

namespace ClassLibraryVoitureTH
{
	public class Roue {

		private int diametre;
		private bool tourne;
		//constructeur par défaut
		public Roue()
		{
			diametre=15;
			tourne=false;

		}
		//constructeur classique
        public Roue(int diametre, bool tourne)
        {
            this.diametre = diametre;
            this.tourne = tourne;
        }
		//constructeur par clonage
		public Roue(Roue _roueACopier )
		{
			diametre = _roueACopier.diametre;
			tourne = _roueACopier.tourne;
		}
		

		public bool Tourner()
		{
			bool aReussiAMettreEnRotation = false;

            if (tourne == false)
            {
				aReussiAMettreEnRotation = true;
				tourne = true;
            }
            else
            {
				aReussiAMettreEnRotation = false;
            }
			return aReussiAMettreEnRotation;
		}

        
    }//end Roue

}//end namespace Voiture