///////////////////////////////////////////////////////////
//  Chrisalyde.cs
//  Implementation of the Class Chrisalyde
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:43:14
//  Original author: pasca
///////////////////////////////////////////////////////////




using ClassLibrary_Lepidoptere;
namespace ClassLibrary_Lepidoptere
{
	public class Chrisalyde : StadEvolution {

		public Chrisalyde(){

		}

		

		public override void SeDeplacer(){

		}

	}//end Chrisalyde

}//end namespace Lepidoptere