///////////////////////////////////////////////////////////
//  Chrisalyde.cs
//  Implementation of the Class Chrisalyde
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:43:14
//  Original author: pasca
///////////////////////////////////////////////////////////




using ClassLibrary_Lepidoptere;
using System;

namespace ClassLibrary_Lepidoptere
{
	public class Chrisalyde : StadEvolution {

		public Chrisalyde(){

		}
		public override StadEvolution DonneLeProchainStade()
		{
			return new Papillon();
		}


		public override void SeDeplacer()
		{
			Console.WriteLine("Je reste accroché!");
		}

	}//end Chrisalyde

}//end namespace Lepidoptere