///////////////////////////////////////////////////////////
//  Papillon.cs
//  Implementation of the Class Papillon
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:43:00
//  Original author: pasca
///////////////////////////////////////////////////////////




using ClassLibrary_Lepidoptere;
using System;

namespace ClassLibrary_Lepidoptere
{
	public class Papillon : StadEvolution {

		public Papillon()
		{

		}
		public override StadEvolution DonneLeProchainStade()
		{
			return new Papillon();
		}

		public override void SeDeplacer()
		{
			Console.WriteLine("Je vole");
		}

	}//end Papillon

}//end namespace Lepidoptere